apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 940168446867.dkr.ecr.ap-southeast-2.amazonaws.com/heco-app
  newName: 940168446867.dkr.ecr.ap-southeast-2.amazonaws.com/heco-app
  newTag: abcdefg
resources:
- ../../base
patchesStrategicMerge:
- heco-deployment-patch.yaml
- heco-service-patch.yaml
