---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: heco-app-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: heco-app
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 30
